apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: {{ include "devops-test.fullname" . }}-mysql
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: seed
              mountPath: /docker-entrypoint-initdb.d
          {{- if .Values.mysql.probes.enabled }}
          startupProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h 127.0.0.1 -u root -p$MYSQL_ROOT_PASSWORD
            {{- toYaml .Values.mysql.probes.startup | nindent 12 }}
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h 127.0.0.1 -u root -p$MYSQL_ROOT_PASSWORD
            {{- toYaml .Values.mysql.probes.readiness | nindent 12 }}
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h 127.0.0.1 -u root -p$MYSQL_ROOT_PASSWORD
            {{- toYaml .Values.mysql.probes.liveness | nindent 12 }}
          {{- end }}
      volumes:
        - name: seed
          configMap:
            name: {{ include "devops-test.fullname" . }}-mysql-seed
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: {{ toYaml .Values.mysql.persistence.accessModes | nindent 10 }}
        resources:
          requests:
            storage: {{ .Values.mysql.persistence.size }}