apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-test.fullname" . }}-web
spec:
  type: {{ .Values.web.service.type }}
  selector:
    app: web
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}