apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-test.fullname" . }}-web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.web.containerPort }}
          env:
            {{- range $key, $value := .Values.web.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}

          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}

          {{- if .Values.web.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.web.readinessProbe.path }}
              port: {{ .Values.web.containerPort }}
            {{- omit .Values.web.readinessProbe "enabled" "path" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.web.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.web.livenessProbe.path }}
              port: {{ .Values.web.containerPort }}
            {{- omit .Values.web.livenessProbe "enabled" "path" | toYaml | nindent 12 }}
          {{- end }}